config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => {
  :registrations => 'users/registrations'
}
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'following' => "relationships#following"
    get 'followers' => "relationships#followers"
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  root 'homes#top'
   get 'home/about' => "homes#show"
   get 'search' => "searchs#search"
   get 'chat/:id' => "chats#show", as: 'chat'
   resources :chats, only: [:create]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
              foreign_key: "follower_id",
                dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
              foreign_key: "followed_id",
                dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  def User.search(search, user_or_book, how_search)
   if user_or_book == "1"
    if how_search == "1"
     User.where(['name LIKE ?', "#{search}"])
    elsif how_search == "2"
     User.where(['name LIKE ?', "#{search}%"])
    elsif how_search == "3"
     User.where(['name LIKE ?', "%#{search}"])
    elsif how_search == "4"
     User.where(['name LIKE ?', "%#{search}%"])
    else
     User.all
    end
   end
  end

  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def create
    super
    UserNotifierMailer.send_signup_email(@user).deliver
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
    render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<h2>User info</h2><br>
  <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
  <table class="table font-weight-bold">
    <tr><th>name</th><td><%= user.name %></td></tr>
    <tr><th>introduction</th><td><%= user.introduction %></td></tr>
    <tr><th>フォロー数</th><td><%= link_to user.following.count, user_following_path(user) %></td></tr>
    <tr><th>フォロワー数</th><td><%= link_to user.followers.count, user_followers_path(user) %></td></tr>
  </table>
    <% if current_user.id == user.id %>
      <%= link_to edit_user_path(user.id) do%>
        <button type="button" class="btn btn-outline-secondary btn-sm w-100">
          <i class="fas fa-user-cog"></i>
        </button>
      <% end %>
    <% else %>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-info" %>
          <% else %>
        <%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success" %>
      <% end %>
    <% end %>
    <div class="chat-btn">
    <% if current_user != user %>
      <%= link_to 'Chatを始める', chat_path(user.id) %>
    <% end %>
    </div>

app/views/users/edit.html.erb
<div class="mx-auto" style="width: 200px;">
  <h2>User info</h2>
    <% if @user.errors.any? %>
      <%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:<br>
      <% @user.errors.full_messages.each do |message| %>
      ・<%= message %><br>
      <% end %>
    <% end %>
  <%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label><br>
    <%= f.text_field :name, autofocus: true, id:"inputName" %><br>
  <label for="inputImage">Image</label><br>
    <%= f.attachment_field :profile_image, autofocus: true, id:"inputImage" %><br>
  <label for="inputIntroduction">Introduction</label><br>
    <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %><br>
    <%= f.submit "Update User", class: "btn btn-secondary mt-2" %>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user %>
      <%= render 'books/list', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <tr class="font-weight-bold">
          <td>image</td>
          <td>name</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user.id) do %>
            <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50' %>
            <% end %>
            </td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.following.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <% if current_user != user %>
          <td>
            <% if current_user.following?(user) %>
             <%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
            <% else %>
             <%= link_to "フォローする", user_relationships_path(user), method: :post %>
            <% end %>
          </td>
          <% end %>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
        <% end %>
      </table>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user %>
      <%= render 'books/list', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table">
          <tr class="font-weight-bold">
            <td></td>
            <td>Title</td>
            <td>Opinion</td>
          </tr>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50' %></td>
              <% end %>
            <td><%= link_to book.title, book_path(book.id) %></th>
            <td><%= book.body %></th>
          </tr>
          <% end %>
          <%= paginate @books %>
        </table>
    </div>
  </div>
</div>