config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => {
  :registrations => 'users/registrations'
}
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'following' => "relationships#following"
    get 'followers' => "relationships#followers"
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  root 'homes#top'
   get 'home/about' => "homes#show"
   get 'search' => "searchs#search"
   get 'chat/:id' => "chats#show", as: 'chat'
   resources :chats, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def Book.search(search, user_or_book, how_search)
   if user_or_book == "2"
    if how_search == "1"
     Book.where(['title LIKE ?', "#{search}"])
    elsif how_search == "2"
     Book.where(['title LIKE ?', "#{search}%"])
    elsif how_search == "3"
     Book.where(['title LIKE ?', "%#{search}"])
    elsif how_search == "4"
     Book.where(['title LIKE ?', "%#{search}%"])
    else
     Book.all
    end
   end
  end

validates :title, presence: true
validates :body, presence: true, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :user_rooms
  has_many :chats

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
              foreign_key: "follower_id",
                dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
              foreign_key: "followed_id",
                dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  def User.search(search, user_or_book, how_search)
   if user_or_book == "1"
    if how_search == "1"
     User.where(['name LIKE ?', "#{search}"])
    elsif how_search == "2"
     User.where(['name LIKE ?', "#{search}%"])
    elsif how_search == "3"
     User.where(['name LIKE ?', "%#{search}"])
    elsif how_search == "4"
     User.where(['name LIKE ?', "%#{search}%"])
    else
     User.all
    end
   end
  end

  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.page(params[:page])
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
    @books = Book.all
    @user = current_user
    render 'index'
    end
  end

  def show
    @books = Book.all
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render 'edit'
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
    render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
  #binding.pry
    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!,except: [:top, :show]
  def top
  end

  def show
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
    render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
<%= form_with url: search_path, method: :get, local: true do |f| %>
 <%= f.text_field :search %>
 <%= f.select(:option, options_for_select([["user", "1"],["book", "2"]])) %>
 <%= f.select(:choice, options_for_select([["完全一致", "1"],["前方一致", "2"],["後方一致", "3"],["部分一致", "4"]])) %>
 <%= f.submit '検索', name: nil %>
 <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white pt-0 pb-0">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand p-3 text-white" href="/">Bookers</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user), class: 'nav-link text-white' do%><i class="fas fa-home"> Home</i><% end %>
              </li>
              <li class="nav-item">
                <%= link_to  users_path, class: 'nav-link text-white' do%><i class="fas fa-users"> Users</i><% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-white' do%><i class="fas fa-book-open"> Books</i><% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do%><i class="fas fa-sign-out-alt"> logout</i><% end %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-white' do%><i class="fas fa-home"> Home</i><% end %>
              </li>
              <li class="nav-item">
                <%= link_to home_about_path, class: 'nav-link text-white' do%><i class="fas fa-link"> About</i><% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-white' do%><i class="fas fa-user-plus"> sign up</i><% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-white' do%><i class="fas fa-sign-in-alt"> login</i><% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <p class="notice text-success"><%= notice %></p>
    <div style="margin: 0 auto;"><%= render 'layouts/search' %></div>
    <%= yield %>
    <footer>
        <p class="text-center mt-5 mb-5">CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>